baseURL = "https://carlogilmar.xyz"
languageCode = "en"
title = "🎨 Blog de @carlogilmar"
theme = "hugo-theme-monochrome"
defaultContentLanguage = "en"
enableEmoji = true
paginate = 5
googleAnalytics = "G-CJXJL083W7"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[outputs]
home = ["HTML", "RSS", "JSON"]
